import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ArrowRight, Award, BookOpen, Zap, Bookmark } from 'lucide-react';
import { useApp } from '../app/providers';
import { points } from '../services/progress';
import { lessons, courses, localized, lessonPath } from '../app/content';
import { ProgressBar } from '../components/ui';
export default function Dashboard() {
 const { t,i18n } = useTranslation(); const { progress,status,sync,user } = useApp(); const last = lessons.find(l => l.id === progress.lastLesson)!;
 return <div className="container page"><div className="section-heading"><div><span className="eyebrow">{t('dashboard')}</span><h1>{t('progressTitle')}</h1><p className="lead">{t('progressDescription')}</p></div><span className="pill" role="status">{t(status)}</span></div><div className="stats"><article><BookOpen/><strong>{progress.completed.length}<small> / {lessons.length}</small></strong><span>{t('lessons')}</span></article><article><Zap/><strong>{points(progress)}</strong><span>{t('points')}</span></article><article><Award/><strong>{courses.filter(c => lessons.filter(l => l.course === c.id && !l.optional).every(l => progress.completed.includes(l.id))).length}</strong><span>{t('courses')}</span></article></div><div className="continue-card"><div><span className="eyebrow">{t('continue')}</span><h2>{localized(last.title,i18n.language)}</h2><p>{localized(last.summary,i18n.language)}</p></div><Link className="button" to={lessonPath(last.id)}>{t('continue')}<ArrowRight size={18}/></Link></div><div className="dashboard-grid"><section className="panel"><h2>{t('courses')}</h2>{courses.map(c => { const list=lessons.filter(l => l.course===c.id); const done=list.filter(l => progress.completed.includes(l.id)).length; return <div className="module-progress" key={c.id}><div><Link to={`/courses/${c.id}`}>{localized(c.title,i18n.language)}</Link><span>{done}/{list.length}</span></div><ProgressBar value={done/list.length*100} label={localized(c.title,i18n.language)}/></div>; })}</section><section className="panel"><h2>{t('achievements')}</h2><div className={`achievement ${progress.completed.length ? 'earned' : ''}`}><Award/><div><strong>{t('firstStep')}</strong><p>{t('firstStepDesc')}</p></div>{progress.completed.length > 0 && <span>✓</span>}</div><h2><Bookmark size={20}/>{t('bookmark')}</h2>{progress.bookmarks.length ? progress.bookmarks.map(id => <p key={id}><Link to={lessonPath(id)}>{localized(lessons.find(l=>l.id===id)!.title,i18n.language)}</Link></p>) : <p className="muted">{t('noBookmarks')}</p>}</section></div>{user && <button className="button secondary" onClick={() => { void sync(); }}>{t('sync')}</button>}</div>;
}
