import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ArrowRight, Check, Terminal, Sparkles, Layers, ChevronRight } from 'lucide-react';
import { courses, lessons, localized, lessonPath } from '../app/content';
import { useApp } from '../app/providers';
import { icons } from '../components/ui';
export function CourseCards({ only }: { only?: string[] }) {
 const { t, i18n } = useTranslation(); const { progress } = useApp();
 return <div className="course-grid">{courses.filter(c => !only || only.includes(c.id)).map((c, i) => { const list = lessons.filter(l => l.course === c.id); const done = list.filter(l => progress.completed.includes(l.id)).length; const Icon = icons[c.icon as keyof typeof icons] || Terminal; return <Link className={`course-card tone-${i % 4}`} key={c.id} to={`/courses/${c.id}`}><div className="card-top"><span className="course-icon"><Icon size={26} aria-hidden/></span><span className="pill">{c.legacy ? t('legacy') : `0${i+1}`}</span></div><h3>{localized(c.title,i18n.language)}</h3><p>{localized(c.description,i18n.language)}</p><div className="card-bottom"><span>{done ? `${done} / ` : ''}{list.length} {t('lessons')}</span><ArrowRight size={20} aria-hidden/></div></Link>; })}</div>;
}
export default function Landing() {
 const { t } = useTranslation(); const { progress } = useApp();
 return <><section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/>{t('heroEyebrow')}</div><h1>{t('heroTitle')}</h1><p className="lead">{t('heroDescription')}</p><div className="actions"><Link className="button" to={lessonPath(progress.lastLesson)}>{t(progress.completed.length ? 'continue' : 'start')}<ArrowRight size={20} aria-hidden/></Link><Link className="text-link" to="/courses">{t('explore')}<ChevronRight size={18} aria-hidden/></Link></div><div className="hero-notes"><span><Check size={16} aria-hidden/>Linux + Git</span><span><Check size={16} aria-hidden/>React + Node.js</span><span><Check size={16} aria-hidden/>ES / EN</span></div></div><div className="hero-visual"><div className="terminal-preview"><div className="terminal-title"><span className="window-dots"><i/><i/><i/></span><span>student@linuxlab: ~</span><Terminal size={15} aria-hidden/></div><div className="terminal-content"><p><b>student</b><span> ~ </span>$ whoami</p><p className="terminal-answer">future-builder</p><p><b>student</b><span> ~ </span>$ cat learning-path.json</p><pre>{'{\n  "start": "curiosity",\n  "tools": ["linux", "git", "react"],\n  "next": "your first deploy"\n}'}</pre><p><b>student</b><span> ~ </span>$ <span className="cursor"/></p></div></div><div className="floating-card"><span className="success-circle"><Check size={20} aria-hidden/></span><div><strong>{t('learnByDoing', { defaultValue: t('tagline') })}</strong><span>{t('feature3')}</span></div></div><span className="visual-label">&lt; build your next chapter /&gt;</span></div></section><section className="path-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">{t('pathEyebrow')}</span><h2>{t('pathTitle')}</h2><p>{t('pathDescription')}</p></div><Link className="text-link" to="/courses">{t('allPaths')}<ArrowRight size={18} aria-hidden/></Link></div><CourseCards only={['foundations','modern','git']}/></div></section><section className="container features"><h2>{t('featuresTitle')}</h2><div className="feature-grid">{[Terminal,Sparkles,Layers].map((Icon,i) => <article key={i}><Icon size={26} aria-hidden/><h3>{t(`feature${i+1}`)}</h3><p>{t(`feature${i+1}Desc`)}</p></article>)}</div><div className="instructor-strip"><img src={`${import.meta.env.BASE_URL}images/perfil.jpg`} onError={e => { e.currentTarget.hidden = true; }} alt="José Pablo Campos"/><div><span className="eyebrow">{t('about')}</span><h3>José Pablo Campos Solano</h3><p>{t('authorDescription')}</p></div><Link className="icon-button" to="/about" aria-label={t('about')}><ArrowRight/></Link></div></section></>;
}
