version = 0.1

[default.global.parameters]
template_file = "cloudformation/lambda.yml"

[default.build.parameters]
use_container = false

[default.deploy.parameters]
stack_name = "linux-lab-prod-linux-lab-progress-lambda"
s3_bucket = "linux-lab-prod-sam-deployments"
s3_prefix = "linux-lab-prod-linux-lab-progress-lambda"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = false
parameter_overrides = "Environment=prod"

[prod.global.parameters]
template_file = "cloudformation/lambda.yml"

[prod.build.parameters]
use_container = false

[prod.deploy.parameters]
stack_name = "linux-lab-prod-linux-lab-progress-lambda"
s3_bucket = "linux-lab-prod-sam-deployments"
s3_prefix = "linux-lab-prod-linux-lab-progress-lambda"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = false
parameter_overrides = "Environment=prod"
