import { spawnSync } from 'node:child_process';
import { readFile,writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
const profile=process.env.AWS_PROFILE||'PACIFIC-PROD',region='us-east-1';
const run=args=>{const r=spawnSync('aws',[...args,'--profile',profile,'--region',region],{encoding:'utf8'});if(r.status!==0)throw new Error(r.stderr||'AWS operation interrupted');return r.stdout.trim();};
const deploy=(template,stack,parameters)=>run(['cloudformation','deploy','--template-file',`infra/${template}.yml`,'--stack-name',stack,'--capabilities','CAPABILITY_IAM','CAPABILITY_NAMED_IAM','--no-fail-on-empty-changeset','--parameter-overrides',...parameters]);
const state=JSON.parse(await readFile('docs/deployment-state.json','utf8')),image=JSON.parse(await readFile('docs/lab-image.json','utf8'));
if(!image.verifiedOffline)throw new Error('Image must pass the offline bake checks');
const actual=JSON.parse(run(['ec2','describe-images','--image-ids',image.imageId,'--owners','self','--output','json']));if(actual.Images[0]?.State!=='available')throw new Error('AMI is not available in this account');
const artifact=await readFile('backend/service/lambda-package.zip');const key=`progress/${createHash('sha256').update(artifact).digest('hex')}.zip`;
run(['s3','cp','backend/service/lambda-package.zip',`s3://${state.ArtifactBucket}/${key}`,'--only-show-errors']);
const resource=id=>run(['cloudformation','describe-stack-resource','--stack-name','linux-lab-progress','--logical-resource-id',id,'--query','StackResourceDetail.PhysicalResourceId','--output','text']);
console.log('Deploying the isolated student network, lifecycle API and server deadlines.');
deploy('temporary-labs','linux-lab-temporary',[`ApiId=${resource('Api')}`,`AuthorizerId=${resource('Authorizer')}`,`ArtifactBucket=${state.ArtifactBucket}`,`ArtifactKey=${key}`,`LabImageId=${image.imageId}`]);
const outputs=Object.fromEntries(JSON.parse(run(['cloudformation','describe-stacks','--stack-name','linux-lab-temporary','--query','Stacks[0].Outputs','--output','json'])).map(o=>[o.OutputKey,o.OutputValue]));
const arn=`arn:aws:lambda:${region}:${state.account}:function:${outputs.FunctionName}`;
deploy('github-backend-oidc','linux-lab-backend-role',[`FunctionArn=arn:aws:lambda:${region}:${state.account}:function:${state.ProgressFunction}`,`LabFunctionArn=${arn}`,`ArtifactBucket=${state.ArtifactBucket}`,`OidcProviderArn=arn:aws:iam::${state.account}:oidc-provider/token.actions.githubusercontent.com`]);
await writeFile('docs/deployment-state.json',JSON.stringify({...state,LabFunction:outputs.FunctionName,LabVpc:outputs.VpcId,LabSubnet:outputs.SubnetId,LabSecurityGroup:outputs.SecurityGroupId,LabSessionsBucket:outputs.SessionsBucketName,LabImageId:image.imageId,LabArtifactKey:key,updated:new Date().toISOString()},null,2)+'\n');
console.log('Temporary labs deployed. Real-instance terminal and teardown smoke checks remain required.');
